make:
	g++ Server/Request.cpp Client.cpp Chat/chat.cpp -std=c++17 -Wall -Wextra -pedantic-errors -o Chat/chat
	g++ Server/Request.cpp Server/server.cpp -o Server/server


server:
	Server/server

chat:
	Chat/chat
